import type { Metadata } from "next";
import { Geist, Geist_Mono, Signika } from "next/font/google";
import Wrapper from "@/components/wrapper/Wrapper";
import "../globals.css";

const signika = Signika({
  subsets: ["latin"],
  weight: ["400", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${signika.className} antialiased`}
        data-new-gr-c-s-check-loaded="14.1268.0"
        data-gr-ext-installed=""
      >
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
